- angular/projects/catalyst/src/lib/catalyst.module.ts
- angular/projects/catalyst/src/public-api.ts
> feat(core): fix value accessor

- CHANGELOG.md
- angular/projects/catalyst/package.json
- core/package.json
- core/src/components/cat-scrollable/cat-scrollable.scss
- package-lock.json
- react/package.json
- tokens/package.json
> chore(release): fix scrollable and publish new catalyst version

- core/src/components/cat-badge/cat-badge.tsx
- core/src/styles/core/_typography.scss
- core/src/utils/setDefault.ts
Fix badge not updating on property changes
> fix(core): fixed bug

- core/src/components/cat-badge/cat-badge.tsx
> fix(core): badge fix

- angular/projects/catalyst-demo/src/app/app.component.html
- angular/projects/catalyst-demo/src/app/app.component.ts
- core/src/components/cat-input/cat-input.tsx
* fix error showing if errorMap changed without an input/blur
> feat(core): input validation

- core/src/components/cat-button/cat-button.scss
- core/src/components/cat-dropdown/cat-dropdown.scss
- core/src/index.html
- core/src/styles/_variables.scss
- core/src/styles/core/_nav.scss
- pnpm-lock.yaml
**Dropdown improvements**
* Re-added a consistent padding to dropdown body (affects inner buttons)
* Changed transition from a "slide fade in" to a "scale fade in"
* Fixed an issue with the transition where the first time opening a dropdown would not trigger the transition
* Added new real life example to stencil page
> feat(core): dropdown improvements

- core/src/components/cat-dropdown/cat-dropdown.scss
- core/src/components/cat-select/cat-select.scss
- core/src/components/cat-tooltip/cat-tooltip.scss
- core/src/styles/_mixins.scss
- core/src/styles/_variables.scss
- core/src/styles/utils/_z-index.mixins.scss
- tokens/src/z-index.json
Note that this does not immediately fix the mentioned bugs, but it gives a generic and agnostic way out by providing a base index via css properties that can be set.
fixes #303
fixes #308
> fix(core): base z-index can now be set via CSS properties

- angular/projects/catalyst/src/lib/directives/proxies.ts
- core/package.json
- core/src/components.d.ts
- core/src/components/cat-datepicker-inline/cat-datepicker-inline.e2e.ts
- core/src/components/cat-datepicker-inline/cat-datepicker-inline.scss
- core/src/components/cat-datepicker-inline/cat-datepicker-inline.spec.tsx
- core/src/components/cat-datepicker-inline/cat-datepicker-inline.tsx
- core/src/components/cat-datepicker-inline/readme.md
- core/src/components/cat-datepicker/cat-datepicker.config.ts
- core/src/components/cat-datepicker/cat-datepicker.format.ts
- core/src/components/cat-datepicker/cat-datepicker.locale.ts
- core/src/components/cat-datepicker/cat-datepicker.mode.ts
- core/src/components/cat-datepicker/cat-datepicker.tsx
- core/src/components/cat-input/cat-input.scss
- core/src/components/cat-input/cat-input.tsx
- core/src/components/cat-textarea/cat-textarea.scss
- core/src/components/cat-textarea/cat-textarea.tsx
- core/src/index.html
- core/src/styles/vendor/_flatpickr.scss
- core/stencil.config.ts
- pnpm-lock.yaml
- react/src/components/stencil-generated/index.ts
- vue/src/components.ts
> feat(core): implement inline datepicker

- core/src/components/cat-tabs/cat-tabs.scss
Adjusted spacings for tabs which align to an edge (first or last).
> feat: minor follow up improvements for tabs

- core/package.json
- core/src/index.html
- core/src/styles/core/_typography.scss
- pnpm-lock.yaml
- New type section
- Smaller adjustments to the top buttons of the page (github, slack)
- Added icon sprite page as a 3rd tab
- Added switch buttons for font and theme
- Initial proposal for typography spacings inside <article> tag
> feat: new type section on overview page

- core/src/styles/index.scss
Motion reduction removes transitions entirely which causes issues with swiper.js
> fix: 21242 (sanitation -> motion reduction)

- pnpm-lock.yaml
> Revert "fix: update lock file"

- pnpm-lock.yaml
> Revert "fix: fix pnpm lock file"

- angular/projects/catalyst/src/lib/catalyst.module.ts
- core/src/components/cat-time/cat-time.tsx
* Added the watch cycle to the cat-time component so it detects value changes and syncs the input value
* Exported the cat-time component since it was not provided before
* cat-time input changes value when a value change is done programmatically
> fix(core): export and fix cat-time value changes

- angular/projects/catalyst-demo/src/app/app.component.html
- core/src/components/cat-tag/cat-tag.tsx
* fixed issue with slot hints
* fixed issue with deleting tags individually
* Changes are correct
> fix(angular): provide fix for missing hint and missing detection

- core/src/styles/core/_notification.scss
> feat(core): notifications on mobile

- angular/projects/catalyst-demo/src/app/app.component.html
- angular/projects/catalyst-demo/src/app/app.component.ts
- angular/projects/catalyst/src/lib/directives/proxies.ts
- core/src/components.d.ts
- core/src/components/cat-spinner/cat-spinner.spec.tsx
- core/src/components/cat-spinner/cat-spinner.tsx
- core/src/components/cat-spinner/readme.md
- vue/src/components.ts
> feat(core): use progressbar role for cat-spinner

- core/src/components/cat-time/cat-time.scss
> feat(core): fixes broken style for cat-time buttons

- angular/projects/catalyst-demo/src/app/app.module.ts
- angular/projects/catalyst/src/lib/datetime/datetime.component.ts
- angular/projects/catalyst/src/lib/directives/date-value-accessor.ts
- angular/projects/catalyst/src/lib/directives/time-value-accessor.ts
> feat(angular): fix required error for datetime control

- angular/projects/catalyst-demo/src/app/app.module.ts
- angular/projects/catalyst/src/lib/dialog/dialog.service.ts
- angular/projects/catalyst/src/public-api.ts
Add the ability to provide custom dialog sizes for consistency.
> feat(angular): add custom dialog size config

- core/src/components/cat-scrollable/cat-scrollable.tsx
1. changed the way how scroll offset is checked for load more event
2. fixed scroll shadow appearance
> fix(core): fixed cat-scrollable for windows
