haiilo/catalyst

core/src/components/cat-menu/cat-menu.tsx
core/src/index.html

[PMI-564](https://coyoapp.atlassian.net/browse/PMI-564)
The bug is due to two things: 
- The first is the hierarchy in the stencil lifecycle: children are loaded before the parent component. `componentDidLoad`
- Second the `tabbable` method does not recognize the elements that are hidden. 
And what happens is that first the cat-menu load is called and then the load of the cat-card and in the load of the cat-menu the element is still hidden (`visibility: inherit`) since cat-card has not yet loaded, when cat-card finishes loading is when it is already visible and the cat-menu trigger is initialized in its load and as I commented, the `firstTabbable` does not detect any element since it has visibility hidden.
If you have any questions let me know.

fix(core): init trigger if not exist

---

core/src/components/cat-input/cat-input.scss

Added our utility cat-ellipsis to the native input element inside the component.
This does not affect the text area component.

feat(core): inputs now use ellipsis when text is truncated

---

core/src/components/cat-card/cat-card.scss
core/src/index.html

I basically just removed the conditional styling for nav elements inside cat-cards as we do not need that anymore.
This would also mean that a card that's supposed to contain a nav element also needs the class "cat-p-xs" to work properly. Is that an acceptable solution or too manual?

chore(core): fixed broken spacings in nav cat-card

---

core/src/components/cat-tooltip/cat-tooltip.tsx

**Description:**
- as in current state tooltips have just a main axis fallback (eg: default placement is top, without enough space on the top side to display the tooltip it will fallback to the bottom side), in case of not enough space on the main axis, by adding `fallbackAxisSideDirection: 'start'`, as part of the options argument of `flip` method, will allow cross axis switch (eg: if not enough space on right side, flips to left side, if not enough space on left side it will flip cross axis to the top side)
**Screenshots:**
| Situation | Before | After |
| ------ | ------ | ------ |
| placement: right - enough space on all sides | ![image](https://github.com/haiilo/catalyst/assets/22702708/12335833-3cec-40b4-815a-6ca46ab3ecf5) | …

fix: add flip fallback axis for tooltips

---

angular/projects/catalyst-demo/src/app/app.component.html
angular/projects/catalyst-demo/src/app/app.component.ts
core/src/components/cat-datepicker/cat-datepicker.tsx

**What:**
Bug fix for the datepicker.
**Steps to reproduce old behavior:**
1. Create a checkbox and a datepicker
2. Set [disabled] attribute to depend on a checkbox. Can be like a reference on a checkbox: #checkbox.checked.
3. Checkbox is set as true
4. Try to click twice on a checkbox fast (might require some attempts)
_Expected result:_ 
datepicker is working (clickable, date can be picked)
_Actual result:_
datepicker is broken. Calendar is not shown, date can't be picked.
Additional info:
Any other approach of using API didn't work as expected. I tried to combine 'disable', 'allowInput' from https://flatpickr.js.org/options/ but nothing worked well. So I accessed altInput which I used to implement the logic.
(on the gif you can see like after clicking twice on a checkbox datepicker …

fix: datepicker disabled state change is unstable

---

angular/projects/catalyst-demo/src/app/app.component.html
core/src/components/cat-datepicker/cat-datepicker.tsx

In order to be able to switch the type of the datepicker dynamically we need to reinstanciate the datepicker like we did for readonly and disabled already.

fix(core): make mode dynamically changeable for datepicker

---

core/src/styles/utils/_layout.scss

* Added utility layout classes for flex-direction reverse options (col and row)
* It works
**Additional Info**
* @fynnfeldpausch I wanted to adjust the documentation [here](https://design.haiilo.com/7a807c8eb/p/069dc7-layout/t/page-069dc7-48935622-2), but I didn't find where to. Can you point me out to it? Thank you.
* It's the first PR I make for Catalyst (I think). So I'm not completely sure of the rules and guidelines. Let me know if there's something more i need to take care of.

feat(core): add reverse flex direction classes

---

core/src/components/cat-select/cat-select.tsx

Currently if user performs a search in catalyst select and search is async action (http request to server), then the list of options is flickering because skeleton is replacing options list during the search. 
As a solution we can show skeleton only when user opens the dropdown panel and do not show it again until it's gonna be closed. That helps to make the search more smooth.

feat(core): do not show skeleton on search in select

---

core/src/components/cat-select/cat-select.tsx

The search input size can be calculated as very small w/o minWidth:true config and I input has placeholder it would be cut off

feat(core): use minWidth: true setting for cat-select input autosize

---

angular/projects/catalyst-demo/src/app/app.component.html
angular/projects/catalyst-demo/src/app/app.component.ts
core/src/components/cat-time/cat-time.tsx
core/src/index.html

Fix an issue where the input value was not changed or been set properly when setting a value programmatically on the cat-time.
This also fix some issues on the 12 hours format where the AM/PM were not being set properly on load. When for example the time was set to PM and we were changing it programmatically to AM time, the AM/PM button was not changed.

fix(core): fix setting value programmatically on cat-time

---

angular/projects/catalyst-demo/src/app/dialog/dialog.component.html
angular/projects/catalyst/src/lib/dialog/dialog.component.scss

A workaround for https://github.com/haiilo/catalyst/issues/569
**What is happening?**
The floating elements of catalyst have the position property as `fixed`. When the elements are inside the dialog the position is calculated with the new container element, but it seems that the new chrome version (129) still sets the viewport as the container. That is to say, the position calculations are ok but when rendering it, the container element is the viewport instead of the dialog.
**What has been done?**
Dialog has been chosen as the new container element. 
https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed_positioning
**What to test?**
- With the Angular project running, check that the floating elements (`cat-dropdown`, `cat-date`, `cat-time`, `cat-tooltip`, `cat-select`, …

fix(angular): fix position of popup cat-elements inside cat-dialog

---

core/src/components/cat-datepicker/cat-datepicker.locale.ts

To reproduce the issue, change your local timzone to Montreal and open calendar. You'll notice that the month is not correct

fix(core): datepicker month locale are not correct

---

core/src/components/cat-dropdown/cat-dropdown.tsx

If menu item opens dialog then the dialog doesn't get the focus because focus trap is still active

fix(core): do not delay dropdown focus trap deactivation

---

core/src/components/cat-time/cat-time.tsx

* set empty value for cat-time onValueChange aka Watch
* Errors are not thrown when deleting or clearing the cat-time input

fix(core): setting empty value in cat-time

---

core/src/components/cat-avatar/cat-avatar.tsx
core/src/components/cat-button/cat-button.tsx
core/src/components/cat-checkbox/cat-checkbox.spec.tsx
core/src/components/cat-checkbox/cat-checkbox.tsx
core/src/components/cat-date-inline/cat-date-inline.spec.tsx
core/src/components/cat-date-inline/cat-date-inline.tsx
core/src/components/cat-date/cat-date.spec.tsx
core/src/components/cat-date/cat-date.tsx
core/src/components/cat-dropdown/cat-dropdown.tsx
core/src/components/cat-input/cat-input.spec.tsx
core/src/components/cat-input/cat-input.tsx
core/src/components/cat-pagination/cat-pagination.spec.tsx
core/src/components/cat-pagination/cat-pagination.tsx
core/src/components/cat-radio/cat-radio.spec.tsx
core/src/components/cat-radio/cat-radio.tsx
core/src/components/cat-select/cat-select.spec.tsx
core/src/components/cat-select/cat-select.tsx
core/src/components/cat-tabs/cat-tabs.spec.tsx
core/src/components/cat-tabs/cat-tabs.tsx
core/src/components/cat-tag/cat-tag.spec.tsx
core/src/components/cat-tag/cat-tag.tsx
core/src/components/cat-textarea/cat-textarea.spec.tsx
core/src/components/cat-textarea/cat-textarea.tsx
core/src/components/cat-time/cat-time.spec.tsx
core/src/components/cat-time/cat-time.tsx
core/src/components/cat-toggle/cat-toggle.spec.tsx
core/src/components/cat-toggle/cat-toggle.tsx

feat(core): make shadow interaction components are recognized as focusable

---

core/src/components/cat-dropdown/cat-dropdown.tsx

If for example dropdown behaves like combobox we would need to "listbox" value instead "true" for aria-haspopup attribute

feat(core): support custom aria-haspopup on cat-dropdown trigger

---

core/src/components/cat-date-inline/cat-date-inline.tsx
core/src/components/cat-date-inline/cat-date-locale.ts

This pull request fixe  the cat date inline month headline because when we switch from locale, as an example switching from DE to US, the index in the array of `locale.months.long` also changed impacting only the US customers, that will see the title showing the previous month:

fix(core): cat-date-inline month display in headline

---

core/src/components/cat-checkbox/cat-checkbox.spec.tsx
core/src/components/cat-checkbox/cat-checkbox.tsx

fixes #655 
There is an issue in Safari for shadow dom components related to focus and blur. When we focus on button, input with type checkbox and some other components (I don't have a full list) the shadow component itself receives blur event.
And in cat-select we are listening blur event and close dropdown when blur triggers.
Unfortunately there is no way to NOT emit blur event in Safari except NOT using delegateFocus parameter in Stencil for child shadow component. I haven't checked yet the Stencil implementation, but seems like they figured out some workaround because if you just check how native shadow components then absence of delegatefocus doesn't change anything.
So far possible solutions which I have in mind:
use polyfill for Safari and add few conditions in Blur event handler …

fix(core): fix multi-select in Safari

---

core/src/components/cat-dropdown/cat-dropdown.tsx

fixes #652 
before introducing shift() middleware
with shift()

feat(core): use shift middleware for dropdown compute position method

---

core/src/components/cat-input/cat-input.e2e.ts
core/src/components/cat-input/cat-input.tsx

**Problem:**
It's currently not possible to input decimal numbers because typing characters like the dot (`.`) or comma (`,`) is either blocked or triggers unexpected behavior. These characters are crucial for _decimal_ input.
While trying to type them, the input is cleared, the cursor jumps to the start, or the input simply does not react. This seems to be a regression, and I've submitted this PR with a potential fix.

feat(core): allow typing decimal numbers in input type number

---

pnpm-lock.yaml
react/package.json

When developer tries to reinstall all dependencies and build the project with preliminarily removed pnpm-lock.yaml. The reason is in conflicted typescript versions in core and react, so I updated the typescript version in react folder + the whole pnpm-lock.yaml file

feat(react): update typescript version in react set of packages

---

angular/projects/catalyst/src/lib/dialog/dialog-header.component.html

* Changed cat-dialog-header subline class from cat-h6 to cat-text-m as requested by @mrkskmn 
* style is correctly applied

fix(angular): change dialog header subline class

---

core/src/components/cat-notification/cat-notification.tsx
core/src/index.html

fixes #764
If you used `autoClose: false` property in cat-notification service, you need to add closeButton: true explicitly now to make the close button shown

feat(core)!: closeButton property in cat-notification service options
